#ifndef _MY_CMD_IOCTLS_H_
#define _MY_CMD_IOCTLS_H_
#include <linux/ioctl.h>

#define MYCMD_IOC_MAGIC							'k'

#define MYCMD_IOC_POINT_RESET					_IO(MYCMD_IOC_MAGIC, 0)
#define MYCMD_IOC_POINT_INC					_IO(MYCMD_IOC_MAGIC, 1)

#define MYCMD_IOC_LEDS_POINT_GET				_IOR(MYCMD_IOC_MAGIC, 2, int)
#define MYCMD_IOC_LEDS_POINT_SET				_IOW(MYCMD_IOC_MAGIC, 3, int)

#define MYCMD_IOC_LEDS_CUR_ON_SET				_IO(MYCMD_IOC_MAGIC, 4)
#define MYCMD_IOC_LEDS_CUR_OFF_SET				_IO(MYCMD_IOC_MAGIC, 5)
#define MYCMD_IOC_LEDS_CUR_STATUS_SET			_IOW(MYCMD_IOC_MAGIC, 6, int)

#define MYCMD_IOC_LEDS_ALL_ON_SET				_IOW(MYCMD_IOC_MAGIC, 7, int)
#define MYCMD_IOC_LEDS_ALL_OFF_SET				_IOW(MYCMD_IOC_MAGIC, 8, int)

#define MYCMD_IOC_X_TEST						_IOWR(MYCMD_IOC_MAGIC, 9, int)

#define MYCMD_IOC_MAXNR							9
#endif
